# Generated by Django 5.1.4 on 2025-02-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='default-slug', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='تگ'),
        ),
    ]
